server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://;serverName=localhost;port=1433;databaseName=flights-tracker-db-01;encrypt=true;trustServerCertificate=true;}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:DB_Password}
    driverClassName: ${SPRING_DATASOURCE_DRIVERClASSNAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 3000

  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml

openai:
  api:
    url : https://api.openai.com/v1/chat/completions
    key : api-key
logging:
  level:
    #root: DEBUG
    liquibase: ERROR
    #org.apache.coyote: DEBUG
    #org.springframework : DEBUG