server:
  port: ${API_PORT:8082}
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://;serverName=localhost;port=1433;databaseName=master;encrypt=true;trustServerCertificate=true;}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:DB_Password}
    driverClassName: ${SPRING_DATASOURCE_DRIVERClASSNAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
