server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      use_sql_comments: true
      generate_statistics: true
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://;serverName=localhost;port=1433;databaseName=flights-tracker-db-01;encrypt=true;trustServerCertificate=true;}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:DB_Password}
    driverClassName: ${SPRING_DATASOURCE_DRIVERClASSNAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 20000
      max-lifetime: 1200000
      validation-timeout: 3000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    parameters:
      lock-wait-time: 300000  # 5 minutes
      change-log-lock-poll-rate: 10000  # 10 secondsmigrar

vitech:
  tracker:
    openai:
      api:
        url : https://api.openai.com/v1/chat/completions
        key: key
        key-statistic : key-statistic

    processor:
      openai:
        enabled: false
        chunk-size: 10
      flight:
        enabled: false
        chunk-size: 10
      airport:
        enabled: false
        chunk-size: 1000
      airport-entity:
        enabled: false
        chunk-size: 1000
      airline:
        enabled: false
        chunk-size: 1000
      range:
        enabled: true
        chunk-size: 1000
      aircraft-type:
        enabled: true
        chunk-size: 1000
    pagination:
      default-page-size: 10
      max-page-size: 100

logging:
  level:
    #root: DEBUG
    io.vitech.flights.tracker: DEBUG
    #liquibase: DEBUG
    #com.zaxxer.hikari: DEBUG
    #org.apache.coyote: DEBUG
    #org.springframework : DEBUG
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate.type: OFF
    org.hibernate: OFF