openapi: 3.0.0
info:
  title: Flight Tracker API
  version: 1.0.0
  description: API for flights, airports, airlines, airplane and cities statistic .

servers:
  - url: http://localhost:8080/api

paths:
  /airports:
    get:
      summary: Get all airports
      responses:
        '200':
          description: A list of airports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
  /airports/{id}:
    get:
      summary: Get an airport by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An airport
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'

  /flights:
    get:
      summary: Get all flights
      responses:
        '200':
          description: A list of flights
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
  /flights/{id}:
    get:
      summary: Get a flight by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A flight
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'

  /cities:
    get:
      summary: Get all cities
      responses:
        '200':
          description: A list of cities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
  /cities/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a city by ID
      responses:
        '200':
          description: A city
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'

  /airlines:
    get:
      summary: Get all airlines
      responses:
        '200':
          description: A list of airlines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airline'
  /airlines/{id}:
    get:
      summary: Get an airline by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An airline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airline'

  /aircrafts:
    get:
      summary: Get all aircrafts
      responses:
        '200':
          description: A list of aircrafts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aircraft'
  /aircrafts/{id}:
    get:
      summary: Get an aircraft by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An aircraft
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aircraft'

components:
  schemas:
    Airport:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        iata_code:
          type: string
        city:
          $ref: '#/components/schemas/City'

    Flight:
      type: object
      properties:
        id:
          type: integer
          format: int64
        flightStatus:
          $ref: '#/components/schemas/FlightStatus'
        arrivalAirport:
          $ref: '#/components/schemas/Airport'
        departureAirport:
          $ref: '#/components/schemas/Airport'
        aircraft:
          $ref: '#/components/schemas/Aircraft'
        flightDate:
          type: string
          format: date-time

    City:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        timezone:
          type: string

    FlightStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string

    Aircraft:
      type: object
      properties:
        id:
          type: integer
          format: int64
        model:
          type: string
        manufacturer:
          type: string

    Airline:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        country:
          type: string