openapi: 3.0.3
info:
  title: Swagger Flights Tracker - OpenAPI 3.0
  version: 1.0.11
paths:
  /hello:
    get:
      summary: Returns a hello message
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
   